"use client";

import Link from "next/link";
import { FormEvent, useState, type ReactNode } from "react";
import { useParams, useRouter } from "next/navigation";
import { useAppData } from "./app-providers";
import { BackIcon, PlusIcon } from "./icons";
import { StatusBadge } from "./status-badge";
import { actualProfit, dateLabel, money, otherCostTotal, plannedProfit, repairTotal, totalCost, vehicleCosts, vehicleRepairs, vehicleSale } from "@/lib/financials";
import type { CostCategory, RepairStatus, VehicleStatus } from "@/lib/types";

const vehicleStatuses: VehicleStatus[] = ["Acheté", "En préparation", "En réparation", "Prêt à vendre", "En vente", "Réservé"];
const repairStatuses: RepairStatus[] = ["À faire", "En cours", "Terminée"];
const categories: CostCategory[] = ["Transport", "Contrôle technique", "Homologation", "Carburant", "Nettoyage", "Publicité", "Pièces", "Taxe", "Autre"];
type Panel = "repair" | "cost" | "sale" | "status" | "edit" | null;

export function VehicleDetail({ sold = false }: { sold?: boolean }) {
  const params = useParams<{ id: string }>(); const router = useRouter(); const { data, ready, addRepair, addCost, sellVehicle, updateVehicle, deleteVehicle } = useAppData();
  const [panel, setPanel] = useState<Panel>(null); const vehicle = data.vehicles.find((item) => item.id === params.id); const sale = vehicle ? vehicleSale(data, vehicle.id) : undefined;
  if (!ready) return <main className="mx-auto min-h-[100dvh] max-w-md bg-[#f7f7f5] p-6 text-sm text-[#718077]">Chargement…</main>;
  if (!vehicle || Boolean(sale) !== sold) return <main className="mx-auto min-h-[100dvh] max-w-md bg-[#f7f7f5] p-6"><Link href={sold ? "/sold" : "/vehicles"} className="text-sm font-bold text-[#1d6144]">Retour à la liste</Link><p className="mt-8 text-[#718077]">Véhicule introuvable.</p></main>;
  const repairs = vehicleRepairs(data, vehicle.id); const costs = vehicleCosts(data, vehicle.id); const cost = totalCost(vehicle, data); const profit = sold ? actualProfit(vehicle, data) : plannedProfit(vehicle, data);
  const remove = () => { if (window.confirm("Supprimer ce véhicule et toutes ses dépenses ? Cette action est irréversible.")) { deleteVehicle(vehicle.id); router.replace("/vehicles"); } };
  return <main className="mx-auto min-h-[100dvh] max-w-md bg-[#f7f7f5] pb-10"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-[#e2e7e2] bg-[#fbfcfa]/95 px-4 py-3 backdrop-blur"><Link href={sold ? "/sold" : "/vehicles"} className="rounded-xl p-2 text-[#355242] active:scale-[.95]"><BackIcon className="h-5 w-5" /></Link><span className="text-sm font-bold">{sold ? "Vente finalisée" : "Fiche véhicule"}</span><button onClick={remove} className={`rounded-lg px-2 py-1 text-xs font-bold ${sold ? "invisible" : "text-red-700"}`}>Supprimer</button></header>
    <div className="px-4 pb-4"><div className="relative -mx-4 aspect-[16/9] bg-[#e8ece7]">{vehicle.photo ? <img src={vehicle.photo} alt={`${vehicle.brand} ${vehicle.model}`} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-sm text-[#708077]">Sans photo</div>}</div><div className="mt-5 flex items-start justify-between gap-3"><div><div className="mb-2">{sold ? <StatusBadge status="Terminée" /> : <StatusBadge status={vehicle.status} />}</div><h1 className="text-3xl font-bold tracking-tight">{vehicle.brand} {vehicle.model}</h1><p className="mt-1 text-sm text-[#718077]">{vehicle.trim || "Version non précisée"} · {vehicle.year || "—"}</p></div>{!sold && <button onClick={() => setPanel("status")} className="rounded-xl border border-[#d8e2da] bg-white px-3 py-2 text-xs font-bold text-[#315d45] active:scale-[.97]">Statut</button>}</div></div>
    <Section title="Résumé financier"><div className="overflow-hidden rounded-2xl border border-[#e1e7e1] bg-white divide-y divide-[#edf0ed]"><MoneyRow label="Prix d’achat" value={money(vehicle.purchasePrice)} /><MoneyRow label="Réparations" value={money(repairTotal(data, vehicle.id))} /><MoneyRow label="Autres coûts" value={money(otherCostTotal(data, vehicle.id))} /><MoneyRow label="Coût total" value={money(cost)} strong /><MoneyRow label={sold ? "Prix de vente" : "Prix de vente prévu"} value={money(sold ? sale!.price : vehicle.targetPrice || 0)} /><MoneyRow label={sold ? "Bénéfice final" : "Bénéfice prévu"} value={money(profit)} strong green /></div></Section>
    <Section title="Informations"><div className="grid grid-cols-2 gap-x-4 gap-y-4 rounded-2xl border border-[#e1e7e1] bg-white p-4 text-sm"><Info label="Carburant" value={vehicle.fuel} /><Info label="Boîte" value={vehicle.transmission} /><Info label="Kilométrage" value={`${vehicle.mileage.toLocaleString("fr-BE")} km`} /><Info label="Date d’achat" value={dateLabel(vehicle.purchaseDate)} /><Info label="Immatriculation" value={vehicle.registration} /><Info label="N° châssis" value={vehicle.vin} /><Info label="Vendeur" value={vehicle.seller} /><Info label="Téléphone" value={vehicle.sellerPhone} /></div>{(vehicle.description || vehicle.notes) && <div className="mt-3 rounded-2xl border border-[#e1e7e1] bg-white p-4 text-sm"><p className="font-bold">Notes</p><p className="mt-2 whitespace-pre-line leading-relaxed text-[#5c6a62]">{vehicle.description}{vehicle.notes && `\n${vehicle.notes}`}</p></div>}</Section>
    <Section title={`Réparations · ${money(repairTotal(data, vehicle.id))}`} action={!sold ? () => setPanel("repair") : undefined}>{repairs.length ? <div className="space-y-2">{repairs.map((repair) => <div key={repair.id} className="rounded-2xl border border-[#e1e7e1] bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-sm">{repair.title}</p><p className="mt-1 text-xs text-[#718077]">{repair.provider || "Prestataire non précisé"} · {dateLabel(repair.date)}</p></div><p className="font-bold text-[#1d6144]">{money(repair.amount)}</p></div><div className="mt-2"><StatusBadge status={repair.status} /></div>{repair.description && <p className="mt-2 text-xs text-[#65736a]">{repair.description}</p>}</div>)}</div> : <Empty label="Aucune réparation ajoutée" />}</Section>
    <Section title={`Autres coûts · ${money(otherCostTotal(data, vehicle.id))}`} action={!sold ? () => setPanel("cost") : undefined}>{costs.length ? <div className="space-y-2">{costs.map((item) => <div key={item.id} className="flex items-start justify-between rounded-2xl border border-[#e1e7e1] bg-white p-4"><div><p className="font-bold text-sm">{item.title}</p><p className="mt-1 text-xs text-[#718077]">{item.category} · {dateLabel(item.date)}</p>{item.comment && <p className="mt-1 text-xs text-[#65736a]">{item.comment}</p>}</div><p className="font-bold text-[#1d6144]">{money(item.amount)}</p></div>)}</div> : <Empty label="Aucun autre coût ajouté" />}</Section>
    {sold ? <Section title="Informations de vente"><div className="rounded-2xl border border-[#e1e7e1] bg-white p-4 text-sm"><Info label="Date de vente" value={dateLabel(sale!.date)} /><div className="my-3 border-t border-[#edf0ed]" /><Info label="Acheteur" value={sale!.buyerName} /><div className="my-3 border-t border-[#edf0ed]" /><Info label="Téléphone" value={sale!.buyerPhone} /><div className="my-3 border-t border-[#edf0ed]" /><Info label="Kilométrage à la vente" value={`${sale!.mileage.toLocaleString("fr-BE")} km`} /></div></Section> : <div className="space-y-3 px-4 pb-4"><button onClick={() => setPanel("sale")} className="w-full rounded-2xl bg-[#1d6144] px-5 py-4 font-bold text-white active:scale-[.98]">Déclarer vendu</button><button onClick={() => setPanel("edit")} className="w-full rounded-2xl border border-[#cfdad1] bg-white px-5 py-3.5 text-sm font-bold text-[#315d45] active:scale-[.98]">Modifier le véhicule</button><p className="text-center text-xs text-[#718077]">Ce véhicule passera dans l’onglet Vendus.</p></div>}
    {panel === "repair" && <RepairPanel close={() => setPanel(null)} add={(value) => { addRepair({ ...value, vehicleId: vehicle.id }); setPanel(null); }} />}{panel === "cost" && <CostPanel close={() => setPanel(null)} add={(value) => { addCost({ ...value, vehicleId: vehicle.id }); setPanel(null); }} />}{panel === "sale" && <SalePanel close={() => setPanel(null)} sell={(value) => { sellVehicle({ ...value, vehicleId: vehicle.id }); router.replace(`/sold/${vehicle.id}`); }} />}{panel === "status" && <StatusPanel close={() => setPanel(null)} status={vehicle.status} update={(status) => { updateVehicle(vehicle.id, { status }); setPanel(null); }} />}{panel === "edit" && <EditPanel vehicle={vehicle} close={() => setPanel(null)} save={(fields) => { updateVehicle(vehicle.id, fields); setPanel(null); }} />}
  </main>;
}
function Section({ title, children, action }: { title: string; children: ReactNode; action?: () => void }) { return <section className="px-4 pb-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold">{title}</h2>{action && <button onClick={action} className="flex items-center gap-1 text-xs font-bold text-[#1d6144]"><PlusIcon className="h-4 w-4" />Ajouter</button>}</div>{children}</section>; }
function Info({ label, value }: { label: string; value?: string }) { return <div><p className="text-xs text-[#78857d]">{label}</p><p className="mt-0.5 font-semibold text-[#293830]">{value || "—"}</p></div>; }
function MoneyRow({ label, value, strong = false, green = false }: { label: string; value: string; strong?: boolean; green?: boolean }) { return <div className={`flex justify-between px-4 py-3 text-sm ${strong ? "font-bold" : ""}`}><span className="text-[#617067]">{label}</span><span className={green ? "text-[#17623d]" : ""}>{value}</span></div>; }
function Empty({ label }: { label: string }) { return <div className="rounded-2xl border border-dashed border-[#d1d9d2] bg-white px-4 py-6 text-center text-sm text-[#718077]">{label}</div>; }
function Panel({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-30 flex items-end bg-[#17251d]/35"><div className="max-h-[88dvh] w-full overflow-y-auto rounded-t-[28px] bg-[#f7f7f5] p-5"><div className="mx-auto mb-4 h-1.5 w-10 rounded-full bg-[#c7d0c9]" /><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={close} className="text-sm font-bold text-[#627268]">Fermer</button></div>{children}</div></div>; }
function RepairPanel({ close, add }: { close: () => void; add: (value: { title: string; description: string; date: string; amount: number; provider: string; status: RepairStatus }) => void }) { const [form, setForm] = useState({ title: "", description: "", date: new Date().toISOString().slice(0, 10), amount: "", provider: "", status: "À faire" as RepairStatus }); return <Panel title="Ajouter une réparation" close={close}><form className="space-y-3" onSubmit={(e: FormEvent) => { e.preventDefault(); add({ ...form, title: form.title.trim(), amount: Number(form.amount) || 0 }); }}><Input label="Titre" value={form.title} set={(title) => setForm({ ...form, title })} placeholder="Ex. changement de pneus" /><Input label="Description" value={form.description} set={(description) => setForm({ ...form, description })} textarea /><div className="grid grid-cols-2 gap-3"><Input label="Date" value={form.date} set={(date) => setForm({ ...form, date })} type="date" /><Input label="Coût" value={form.amount} set={(amount) => setForm({ ...form, amount })} inputMode="decimal" /></div><Input label="Garage ou mécanicien" value={form.provider} set={(provider) => setForm({ ...form, provider })} /><label className="block text-xs font-semibold text-[#526259]">Statut<select className="mt-2" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as RepairStatus })}>{repairStatuses.map((item) => <option key={item}>{item}</option>)}</select></label><Save label="Ajouter la réparation" /></form></Panel>; }
function CostPanel({ close, add }: { close: () => void; add: (value: { title: string; category: CostCategory; amount: number; date: string; comment: string }) => void }) { const [form, setForm] = useState({ title: "", category: "Autre" as CostCategory, amount: "", date: new Date().toISOString().slice(0, 10), comment: "" }); return <Panel title="Ajouter un coût" close={close}><form className="space-y-3" onSubmit={(e: FormEvent) => { e.preventDefault(); add({ ...form, title: form.title.trim(), amount: Number(form.amount) || 0 }); }}><Input label="Titre" value={form.title} set={(title) => setForm({ ...form, title })} placeholder="Ex. carburant retour" /><label className="block text-xs font-semibold text-[#526259]">Catégorie<select className="mt-2" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as CostCategory })}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><Input label="Montant" value={form.amount} set={(amount) => setForm({ ...form, amount })} inputMode="decimal" /><Input label="Date" value={form.date} set={(date) => setForm({ ...form, date })} type="date" /></div><Input label="Commentaire" value={form.comment} set={(comment) => setForm({ ...form, comment })} textarea /><Save label="Ajouter le coût" /></form></Panel>; }
function SalePanel({ close, sell }: { close: () => void; sell: (value: { date: string; price: number; buyerName: string; buyerPhone: string; mileage: number; comment: string }) => void }) { const [form, setForm] = useState({ date: new Date().toISOString().slice(0, 10), price: "", buyerName: "", buyerPhone: "", mileage: "", comment: "" }); return <Panel title="Déclarer vendu" close={close}><form className="space-y-3" onSubmit={(e: FormEvent) => { e.preventDefault(); sell({ ...form, price: Number(form.price) || 0, mileage: Number(form.mileage) || 0 }); }}><p className="rounded-xl bg-[#e7f1eb] p-3 text-xs leading-relaxed text-[#315d45]">Après validation, le véhicule sortira du stock. Les informations restent consultables dans Vendus.</p><div className="grid grid-cols-2 gap-3"><Input label="Date de vente" value={form.date} set={(date) => setForm({ ...form, date })} type="date" /><Input label="Prix de vente réel" value={form.price} set={(price) => setForm({ ...form, price })} inputMode="decimal" /></div><Input label="Nom de l’acheteur" value={form.buyerName} set={(buyerName) => setForm({ ...form, buyerName })} /><div className="grid grid-cols-2 gap-3"><Input label="Téléphone" value={form.buyerPhone} set={(buyerPhone) => setForm({ ...form, buyerPhone })} type="tel" /><Input label="Kilométrage à la vente" value={form.mileage} set={(mileage) => setForm({ ...form, mileage })} inputMode="numeric" /></div><Input label="Commentaire" value={form.comment} set={(comment) => setForm({ ...form, comment })} textarea /><Save label="Confirmer la vente" /></form></Panel>; }
function StatusPanel({ close, status, update }: { close: () => void; status: VehicleStatus; update: (status: VehicleStatus) => void }) { return <Panel title="Changer le statut" close={close}><div className="space-y-2">{vehicleStatuses.map((item) => <button key={item} onClick={() => update(item)} className={`flex w-full items-center justify-between rounded-xl border px-4 py-3 text-sm font-bold active:scale-[.98] ${status === item ? "border-[#2b704f] bg-[#e3efe8] text-[#1d6144]" : "border-[#e1e7e1] bg-white"}`}>{item}{status === item && <span>Actuel</span>}</button>)}</div></Panel>; }
function EditPanel({ vehicle, close, save }: { vehicle: { mileage: number; purchasePrice: number; targetPrice?: number; notes: string; registration: string; seller: string; sellerPhone: string }; close: () => void; save: (fields: { mileage: number; purchasePrice: number; targetPrice?: number; notes: string; registration: string; seller: string; sellerPhone: string }) => void }) { const [form, setForm] = useState({ mileage: String(vehicle.mileage), purchasePrice: String(vehicle.purchasePrice), targetPrice: String(vehicle.targetPrice || ""), notes: vehicle.notes, registration: vehicle.registration, seller: vehicle.seller, sellerPhone: vehicle.sellerPhone }); return <Panel title="Modifier le véhicule" close={close}><form className="space-y-3" onSubmit={(e: FormEvent) => { e.preventDefault(); save({ ...form, mileage: Number(form.mileage) || 0, purchasePrice: Number(form.purchasePrice) || 0, targetPrice: Number(form.targetPrice) || undefined }); }}><div className="grid grid-cols-2 gap-3"><Input label="Kilométrage" value={form.mileage} set={(mileage) => setForm({ ...form, mileage })} inputMode="numeric" /><Input label="Prix d’achat" value={form.purchasePrice} set={(purchasePrice) => setForm({ ...form, purchasePrice })} inputMode="decimal" /></div><Input label="Prix de vente prévu" value={form.targetPrice} set={(targetPrice) => setForm({ ...form, targetPrice })} inputMode="decimal" /><Input label="Immatriculation" value={form.registration} set={(registration) => setForm({ ...form, registration })} /><div className="grid grid-cols-2 gap-3"><Input label="Vendeur" value={form.seller} set={(seller) => setForm({ ...form, seller })} /><Input label="Téléphone" value={form.sellerPhone} set={(sellerPhone) => setForm({ ...form, sellerPhone })} /></div><Input label="Notes privées" value={form.notes} set={(notes) => setForm({ ...form, notes })} textarea /><Save label="Enregistrer les modifications" /></form></Panel>; }
function Input({ label, value, set, placeholder, type = "text", inputMode, textarea }: { label: string; value: string; set: (value: string) => void; placeholder?: string; type?: string; inputMode?: "decimal" | "numeric"; textarea?: boolean }) { return <label className="block text-xs font-semibold text-[#526259]">{label}{textarea ? <textarea className="mt-2" rows={3} value={value} onChange={(e) => set(e.target.value)} placeholder={placeholder} /> : <input className="mt-2" type={type} inputMode={inputMode} value={value} onChange={(e) => set(e.target.value)} placeholder={placeholder} />}</label>; }
function Save({ label }: { label: string }) { return <button className="mt-2 w-full rounded-2xl bg-[#1d6144] px-4 py-4 font-bold text-white active:scale-[.98]">{label}</button>; }
